mysql:
  host: 10.10.20.76
  port: 5432
  user: root
  pw: test
  db: helpdesk_new

log:
  log_name: response.log
  log_sieze_bytes: 5000
  ROLLOVER: midnight
  INTERVAL: 1
  BACKUP_COUNT: 30

email-server:
  server: smtp.gmail.com
  username: ''
  password: ''
  use_ssl: False
  use_tls: True
  port: 587
